### ISSUE TITLE
[Keepass 2.45][KeePassRPC 1.13] After a while Kee stops auto-filling passwords

### ISSUE THREAD

**Issue by baloan** [kee-org/keepassrpc#109] opened 2020-08-18 15:02 UTC
After a while Kee stops auto-filling passwords. When I restart Keepass it works again. I am not even sure this is a Keepass/KeepassRPC or Firefox/Kee addon issue. Is there a good way, i.e. checking log files, to find out?

**Comment by TheDom42** [comment] 2020-10-26 08:38
Could be, that I'm experiencing the same issue: for a few days now I noticed, that on a large number of sites, my passwords were not autofilled anymore (confirmed working a few weeks ago). When I then use the auto-type feature from KeePass, Kee flashes yellow as if to indicate that it wants to save the "new" password. I seems as if there might be problem recognizing the URL field in KeePass. But I also don't know where to start investigating.

**Comment by OnkelTom01** [comment] 2021-02-04 14:23
Same for me!
After synchonizing the database via sftp (IOProtocolExt) with my server the Firefox Kee Addon stops autofill and the Key signs at the end of the fields doesn't appear anymore. After restarting Keepass all worked fine again. But it's not comfortable to restart Keepass every time I synced my database.
Hope this could be fixed in the next update.

**Comment by Nama** [comment] 2021-02-26 13:15
I don't have this issue, but I just wanted to write one, cause Kee can't connect to KeepassRPC after I restarted Keepass once...
But since you don't have this problem... I don't know anymore...

**Comment by luckyrat** [comment] 2023-08-04 11:39
If you're still having trouble, please see the [Kee community forum](https://forum.kee.pm/), especially the [Troubleshooting](https://forum.kee.pm/t/troubleshooting/560) documentation. In future, using the community forum will likely result in faster help (I've just added a GitHub issue template to make that clearer for people arriving at this repo from routes that don't already mention that).

**Closed as completed by luckyrat** 2023-08-04 11:39 UTC
