### ISSUE TITLE
Fill {REF:P@I:} characters instead of the password of UUID

### ISSUE THREAD

**Issue by crise1929** [kee-org/keepassrpc#55] opened 2018-08-06 14:56 UTC
Hello,
I'm using a Windows 10 Pro with Firefox v61.0.1 64 bits with the extension Kee and a Keepass v2.37 with plugin KeePassRPC.

I'm using reference in some password fields like this : {REF:P@I:6AE09F8...}
When the extension Kee filled a pssword field on web page, it's the characters {REF:P@I:6AE09F8...} instead of the password that returned in the box.

Anybody have the same issue? Maybe is just a setting that I missed.

**Comment by dlech** [comment] 2018-08-06 15:07
Duplicate of #32, #37, #40 #47, #49, #51

**Closed as completed** 2018-08-06 20:51 UTC
