### ISSUE TITLE
Incompatibility keepass 2.45 and keepassrpc 1.13.0

### ISSUE THREAD

**Issue by luckyconsultant** [kee-org/keepassrpc#107] opened 2020-08-07 16:34 UTC
With that keepass version I get an error message, 
What versions go together?

**Comment by Havokdan** [comment] 2020-08-13 11:26
They are working well here with me.

**Comment by EamonNerbonne** [comment] 2020-08-17 07:43
It's not really working well for me either, on startup I get an error starting with the following relevant looking bits:

- KeePassRPC requires this port to be available 
- [...] An attempt was made to access a socket in a way forbidden by its access permissions

I'm also have the OpenVPN client installed, and on a hunch I deleted all OpenVPN tap adapters (virtual network cards, basically) - and then keepass 2.45 and keepassrpc 1.13.0 start fine!  Without TAP adapters, OpenVPN is useless, alas.

While keepass is running, I can recreate and use TAP adapters, but it's obviously not ideal.

I've had this occur several times now, but I'm not 100% sure whether it's entirely reproducible since it's an annoying hassle to try out.

**Comment by EamonNerbonne** [comment] 2020-08-17 07:49
The weird thing is, once I do this - it continues working, even after keepass restart.  But I've still seen it happen several times (over the span of months), so... something somewhere is stateful.  Lovely.

**Comment by kohtala** [comment] 2020-08-17 08:37
I just upgraded too and had no problems regards compatibility with these versions.

Please, @luckyconsultant, either provide more information or close this issue.

**Comment by imdataconsult** [comment] 2020-08-19 10:50
Thanks 
I installed everything from scratch and it worked ...

**Comment by imdataconsult** [comment] 2020-08-19 10:56
CloseIssueInput

**Comment by soupersauce** [comment] 2020-08-26 05:23
I am also experiencing this error. Full text below:
\---------------------------

\---------------------------
KeePassRPC could not start listening for connections. To allow KeePassRPC clients (e.g. Kee in your web browser) to connect to this instance of KeePass, please fix the problem indicated in the technical detail below and restart KeePass.

KeePassRPC requires this port to be available: 12546. Technical detail: System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions

   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)

   at System.Net.Sockets.Socket.Bind(EndPoint localEP)

   at Fleck2.WebSocketServer.Start(Action`1 config)

   at KeePassRPC.KeePassRPCServer.StartWebsockServer(WebSocketServerConfig config)

   at KeePassRPC.KeePassRPCServer..ctor(KeePassRPCService service, KeePassRPCExt keePassRPCPlugin, WebSocketServerConfig websocketConfig)

   at KeePassRPC.KeePassRPCExt.Initialize(IPluginHost host)
\---------------------------
OK   
\---------------------------

It didn't start happening immediately after updating keepassrpc but rather randomly out of the blue.

Going on @EamonNerbonne findings I disabled my VPN adapters, started keepass. It started fine without the error and keepassrpc works as expected.

**Comment by EamonNerbonne** [comment] 2020-08-26 11:13
@soupersauce I'm sure this used to work fine with VPN adapters, but I can't remember exactly when this issue started - do you remember any details?  If we knew if it were a keepass change vs. a windows update vs. an openvpn update, that might help narrow things down...

**Comment by EamonNerbonne** [comment] 2020-08-26 11:14
(And I'm not sure if @luckyconsultant / @imdataconsult had this same error message either, I'm just guessing because I happened to have a new error around the same time?)

**Comment by soupersauce** [comment] 2020-08-26 19:39
@EamonNerbonne I first experienced the issue yesterday. I had been on that build of Windows for at least 3 or 4 days. I'm on the dev Windows Insider channel. I've since updated after I got keepassrpc running. Currently version 2004, Build 20197.1000.
I updated both Keepass and keepassrpc basically right as they came out so I've been using the lastest for a few weeks. I'm actually using Forticlient for my VPN, though I wouldn't be surprised if the adapter drivers it uses are the same OpenVPN uses. I've been on that same version for months now. I use the VPN and Keepass every single day and as far as I can remember I haven't made any recent changes that I think can could be related. It really does seem like the error's popped up at random.

**Comment by EamonNerbonne** [comment] 2020-08-27 06:51
That matches my experience pretty closely too, with a few small differences - updated keepass(rpc) promptly; error did not occur immediately after windows update (but fairly soon after, and right after a reboot, which makes sense since that's when I start keepass); however am running 10.0.19041 Build 19041 (not insider but still version 2004).  This is the second time I've had the bug, which first occurred at least a month or two ago (probably already 2004 then though) but I didn't look too carefully the first time around.  But I struggle to think of any immediate cause, too.

Oh well, next time I'll try to more carefully note exactly what happened just before.

**Comment by FabianNiehaus** [comment] 2020-11-21 13:53
You can try the (temporary) workaround I posted in #113 ([Link to comment](https://github.com/kee-org/keepassrpc/issues/113#issuecomment-731582460)).

**Comment by EamonNerbonne** [comment] 2020-11-23 08:04
Thanks! following a few of the comment-links there, the fix in https://github.com/docker/for-win/issues/3171#issuecomment-572571882 seems to have worked for me (so far; knock on wood!)

**Comment by luckyrat** [comment] 2023-08-04 11:50
There are no known incompatibilities with recent KeePassRPC and KeePass versions so the solution likely lies with making other changes to your system. If you're still having trouble, please see the [Kee community forum](https://forum.kee.pm/), especially the [Troubleshooting](https://forum.kee.pm/t/troubleshooting/560) documentation.

**Closed as completed by luckyrat** 2023-08-04 11:50 UTC
