### ISSUE TITLE
Handling placeholders when a second form is raised

### ISSUE THREAD

**Issue by AlphaScorpii-dev** [kee-org/keepassrpc#45] opened 2018-05-27 11:20 UTC
I could successfully set up TOTP input with the latest Kee using the placeholder created by Keeotp, for several sites already. I noticed that for those sites, the form id was the same for both the name/password, and then for the totp number.

When trying to set it up for other sites, like Amazon, Google, I met the problem that the new form raised to ask for the totp is not the same anymore (different form id).
I kind of suspect that I need to set up Kee so that the form is detected again, by adding new keywords in the whitelist, but I couldn't go that far just yet. Am I moving in the right direction or did I just miss something plain obvious ?

I have also troubles understanding what the "page" field stands for exactly in the "form fields" tab of my entry.

**Comment by Pantamis** [comment] 2018-06-14 23:24
Hi,

I also have difficulties to login on google account or dropbox (or github). The username/password step is filled with the expected behavior however not the TOTP step.

At the step of TOTP code Kee seems to detect an entry for a form (it proposes to look at the corresponding entries) but cannot fill the text field.

In google for example, even if I create a new field for KeePassRPC entry with "totpid" for name and ID of text field (name and ID in source code of login page) there is no Kee logo in the text fields and the best way I have to complete it is to copy the TOTP in the proposed entry in Kee menu and paste it by hand.

I precise that the {TOTP} placeholder is working, if I declare it as username it fills username with TOTP in firefox (which is irrelevent but only to test the placeholder and the form fields in KeePassRPC).

Also, I don't understand at all what the use of page field in KeePassRPC neither, I did not find any documentation about what it does.

My setup : 
- Firefox 60.0.2
- KeePass 2.39.1
- KeePassRPC 1.8
- Kee 2.3.19.1

Notice : Maybe the place of this issue is more appropriate in forum.kee.pm as it is mostly related to Kee convenience, I may move it later.

**Comment by AlphaScorpii-dev** [comment] 2018-06-15 07:42
What I had to do on my side to make it work was to add the form field ids to my Kee configuration.

![image](https://user-images.githubusercontent.com/12093095/41456216-b509edde-70ba-11e8-971d-240c81355539.png)

Then referencing the field works, once the form is detected.

![image](https://user-images.githubusercontent.com/12093095/41456289-f334dad8-70ba-11e8-97df-0f321524a91c.png)

I think the problem with Google for instance, is that the form that will received the TOTP code has not the same id than the one requesting username/password.
However, I still don't really know what the "page" column is for.

**Comment by Pantamis** [comment] 2018-06-15 17:05
Hi,

Thank you very much for sharing. 

I had tried your solution before (everything was configured as you show) and it was not working but then i realized that I added space after comma and Kee was not recognizing the fields because of that !!

So now it is clear (just remove the space) I think I will raise the issue of the design of white-list of forms because even if it works once you configure it, the way we add fields and how it handles them is not really convenient neither clear.
And yeah, "page" fields doesn't do anything still.

But thank you for sharing again since now all works for me, Kee and KeePassRPC are really the best tools for browser integration definitively :)

**Comment by luckyrat** [comment] 2018-06-17 09:59
Yeah this is probably not a KeePassRPC issue so I'll close it now but @Pantamis is right in his comment on the forum that it's worth linking the concepts of placeholders and whitelisting because Kee will only attempt to fill in forms it's reasonably sure are username or password fields (TOTP fields therefore are often ignored when not part of a single username/password form).

I've also responded on the forum: https://forum.kee.pm/t/whitelisting-or-blacklisting-forms/1044/5

PS: The page field used to be for KeeFox to enable automatic multi-page logins but it hasn't been possible to replicate that feature in the rewrite for Firefox 57+ so until/unless a further announcement is made about that feature, assume it has no effect on anything.

**Closed as completed by luckyrat** 2018-06-17 09:59 UTC
