### ISSUE TITLE
keepassrpc deletes database file

### ISSUE THREAD

**Issue by abeham** [kee-org/keepassrpc#13] opened 2017-11-28 15:06 UTC
I have KeePass 2.37 installed with Kee 2.0.0.25 and Keepassrpc (I don't see the version, but I downloaded 2 hours ago).
I installed the keepassrpc plugin and KeeFox in Firefox. I got a never ending amount of database connection dialogs. Each time I inserted the password that KeePass displayed, Kee opened a new tab and asked for a new password which KeePass showed. In the end I closed Firefox to exit this loop. I closed KeePass and then my password file was lost. It simply got deleted. I have it in a Dropbox (luckily) and there I saw that it was deleted.

This is a serious issue! Other people could lose their key files. I disabled the Autosave option which was enabled by default. Then I could connect Kee to KeePass without problems, the password connection dialog was displayed only once. I think Autosave does not work. I also had keepasshttp and the corresponding firefox plugin installed at the same time, but these were disconnected (which is why I tried keepassrpc and Kee). I don't think this caused interference.

**Comment by luckyrat** [comment] 2018-04-15 17:48
Sounds like this might be resolved by the changes to file transaction handling to better cope with sync clients like DropBox when KeePass 2.39 is released. In any case, it's nothing to do with KeePassRPC.

If you're still struggling with authentication problems with Kee though, there have been a few similar issues reported so if you search the [forum ](https://forum.kee.pm) you might find the cause of your issue and be able to resolve it.

**Closed as completed by luckyrat** 2018-04-15 17:48 UTC
Labels: invalid
