### ISSUE TITLE
v1.8 Issue with password reference

### ISSUE THREAD

**Issue by proxymus** [kee-org/keepassrpc#32] opened 2018-04-27 06:26 UTC
Hello,

I've noticed an issue with the v1.8 release and entries which are using Field References. In my case they are not replaced, because the entered password is to long. Is this a known bug? It was working with v1.7.3.

Regards

Proxymus

**Comment by luckyrat** [comment] 2018-04-27 07:51
How long is too long?

Can you provide some steps to reproduce the problem?

**Comment by proxymus** [comment] 2018-04-27 08:05
My Password for this URL is 9 characters long. The value which is entered is longer, that's why I assume that the reference value is entered.

![2018-04-27 10_01_02-welcome](https://user-images.githubusercontent.com/1539498/39351590-48db5cbc-4a02-11e8-8cfa-c722ade69515.png)

![2018-04-27 10_02_33-eintrag bearbeiten](https://user-images.githubusercontent.com/1539498/39351591-49177170-4a02-11e8-81bf-bc21af1349aa.png)

**Comment by luckyrat** [comment] 2018-04-27 10:25
It works for me. I notice that you had this same configuration for 1.7.3. Did you remember to enable placeholder processing for that form field?

There will be instructions on how to do that at https://forum.kee.pm/t/placeholder-handling/1100 one day but I don't have time at the moment so unless someone else can do it, you'll have to work out the step by step instructions yourself.

**Comment by proxymus** [comment] 2018-04-27 12:20
Thank you for your hint.

> It works for me. I notice that you had this same configuration for 1.7.3. Did you remember to enable placeholder processing for that form field?

Unfortunately not because it was working with the version before. I've enabled it for the specific entry and now I'm able to login again.

Steps to get it working

Open and edit the specific entry in KeePass.

![grafik](https://user-images.githubusercontent.com/1539498/39361859-8612433a-4a24-11e8-993b-672c0aa36c48.png)
![grafik](https://user-images.githubusercontent.com/1539498/39361941-e1861e76-4a24-11e8-9cf2-c24e3f97e109.png)
![grafik](https://user-images.githubusercontent.com/1539498/39361999-19bccfa6-4a25-11e8-8498-f51589b3ab67.png)

I'm are using Field References very often. The current way to get it working would result in enabling it for all entries which uses references. I assume that it will end that I will enabling it globally for the whole database.
I don't see a security improvement in the current implementation.

**Comment by strasharo** [comment] 2018-04-30 13:41
I have the same issue since I updated to the latest keepasrpc. It no longer gets the value for the referenced fields. It was working prior the upgrade. After I enabled the option above it started working again.

**Comment by m2u-84** [comment] 2018-05-01 20:48
Same here, also not working anymore since the update. Had no problems before. My DB has 300+ entries, so manually re-enabling each and every is not really an option…

EDIT: This seems to be the reason. Still unclear how reasonably regain autofill for all fields, that had it before, without enabling it globally.

**Comment by proxymus** [comment] 2018-05-02 05:12
You can change it globally. In KeePass go to: File -> Database Settings -> Kee

![grafik](https://user-images.githubusercontent.com/1539498/39506314-0b05ecca-4dd8-11e8-8b82-66a122186abf.png)

**Comment by luckyrat** [comment] 2018-05-02 09:10
I've added the instructions for enabling individual form fields now to https://forum.kee.pm/t/placeholder-handling/1100

This change (and the link to the documentation that includes the reasoning and instructions) are explained in the [release notes](https://forum.kee.pm/t/release-notes-keepassrpc-1-8-0/1107) that are on the download page for version 1.8.

Thanks to @proxymus for the screenshots.

I'm going to lock this thread now since all necessary information should already be on the [community forum](https://forum.kee.pm) but if not, feel free to create a new post there.

**Closed as completed by luckyrat** 2018-05-02 09:10 UTC
