### ISSUE TITLE
Incompatibility with KeePassRPC 1.8.0

### ISSUE THREAD

**Issue by ntnsndr** [kee-org/keepassrpc#53] opened 2018-07-02 16:20 UTC
Several of us are experiencing incompatibility between the latest versions of KeePass2 and KeePassRPC on Ubuntu distros. [Details are here](https://forum.kee.pm/t/incompatibility-with-keepassrpc-1-8-0/1328). Thanks for taking the time to consider this.

**Comment by dlech** [comment] 2018-07-02 16:46
Do you have all of the packages listed [here](https://github.com/kee-org/KeeFox/wiki/en-%7C-Installation-%7C-Linux#install-keepassrpc-manually) installed?

**Comment by tadd** [comment] 2018-07-03 01:20
I got the same error in Debian testing.  With `--debug` launch, I got error log in `/tmp/tmp*` like:

```
error CS0006: Metadata file `System.Management.dll' could not be found
```

So I `apt search`-ed and found `libmono-system-management4.0-cil` package.
After `apt install libmono-system-management4.0-cil`, the problem was resolved.

Hope this helps.

**Comment by Darkilen** [comment] 2018-07-03 09:29
I got the same error in Ubuntu `16.04` after updating keepass2 from `2.38` to `2.39.1`.

I update KeePassRPC to `1.8.0` and now, it's works ! (see [release notes](https://forum.kee.pm/t/release-notes-keepassrpc-1-8-0/1107) and [Updating KeePassRPC](https://forum.kee.pm/t/upgrading-keepassrpc/22))

**Comment by ntnsndr** [comment] 2018-07-03 17:03
Darn, that's not working for me on 2.39.1, @Darkilen. Same issue. That's what I did before.

**Comment by Kerberus35** [comment] 2018-07-03 18:29
Updating to KeePassRPC 1.8.0 fixed the error on Ubuntu 16.04 for me

**Comment by jg-development** [comment] 2018-07-04 17:40
Hi,
I`ve got the same problem with keepass2 2.39.1 on ubuntu 18.04 and 1.8.0.
Any ideas?

**Comment by jg-development** [comment] 2018-07-04 17:42
.... and after remove all plugins and reinstall it works ... strange

**Comment by hoshikisa** [comment] 2018-07-05 18:52
For me the problem is still here and kee is not usable.
I removed all my plugins and downloaded the new KeePassRPC 1.8.0 to put it in /usr/lib/keepass2/Plugins/ folder and I restarted keepass and firefox but I still have the error message.
I am using it on Kubuntu 14.04 64 bits with firefox 61 and the version number of keepass 2 is 2.39.1.
When I use the commande keepass2 --debug , I have the following error message : 
![error_message](https://user-images.githubusercontent.com/40869348/42342054-510764e8-8095-11e8-91b2-006245fccb31.png)

**Comment by maffelbaffel** [comment] 2018-07-08 08:04
@tadd This also resolved the issue for me. Thx!

**Comment by ntnsndr** [comment] 2018-07-08 16:54
@tadd's suggestion doesn't work for me, including after removing and re-installing KeePass2.

**Comment by boldt** [comment] 2018-07-09 09:29
I get the same message as @hoshikisa (on Ubuntu 14.04.5 LTS) with `keepass2 --debug`

EDIT: 2018-07-17

For now, I switched back to 2.38.

**Comment by vollbrecht-work** [comment] 2018-07-12 11:58
I think i have the same problem, my output of :/keepass2 -debug 
![bildschirmfoto von 2018-07-12 13-57-41](https://user-images.githubusercontent.com/39002042/42631843-aa527c40-85db-11e8-9ace-6a3d091026cc.png)

**Comment by dvictori** [comment] 2018-07-25 01:24
Also seeing similar problem. Ubuntu 18.06. Keepass2 installed from jtaylor PPA. Using latest Kee plugin. Tried installing the same mono packages mentioned by @tadd with no luck.

Temp file created from the debug option is empty. But I get the following message:

![screenshot from 2018-07-24 22-21-17](https://user-images.githubusercontent.com/5786553/43174377-12991e54-8f90-11e8-93ad-7a2d2e72e46d.png)

**Comment by dlech** [comment] 2018-07-25 02:11
For those who are getting an empty file when using the `--debug` option to `KeePass.exe`, please open an issue on the official KeePass forum. We can't know what is going on with the KeePassRPC extension without more information. But if the debug log file is not working, that is probably a core KeePass issue rather than a KeePassRPC issue. Once that is sorted, then we can hopefully figure out what is going on here.

**Comment by dlech** [comment] 2018-07-25 02:13
And actually, here is a post that looks related: https://sourceforge.net/p/keepass/discussion/329221/thread/43776503/?limit=25#d7cc

**Comment by dlech** [comment] 2018-07-25 02:15
The key things I get from this are:
1. Maybe `mono-complete` no longer includes all of the packages installed by `mono-devel`, so try installing `mono-devel`
2. If that doesn't work, try upgrading mono by using the mono projects package archive.

**Comment by dvictori** [comment] 2018-07-25 12:21
Installing `mono-devel` did the trick. I could then load KeePass and the plugin got compiled. After that I even removed `mono-devel` and other packages installed along with it and things are still working. So, in case someone does not want / need the mono-devel packages, it could be installed just for compiling and then latter, removed.

**Comment by vollbrecht-work** [comment] 2018-07-26 10:47
installing mono-devel worked for me too

**Comment by vldu** [comment] 2018-07-26 19:39
For those who have this problem on Ubuntu 14.04 - you need to upgrade your mono installation

Installation instructions for mono (stable version) can be found on https://www.mono-project.com/download/stable/

After upgrade, keepass2 (2.39.1) + KeePassRPC (1.8.0) should work together.

**Comment by hoshikisa** [comment] 2018-07-29 07:55
The solution of vidu worked for me, thank's a lot :)

**Comment by jgorres** [comment] 2018-08-09 16:52
Installing mono-devel worked for me as well on a Kubuntu 18.04.1.

Thanks.

**Comment by jtoman** [comment] 2018-09-05 18:47
Adding mono-devel does _not_ fix the problem here.

**Comment by dd8zc** [comment] 2018-12-29 13:17
You really should put this in a FAQ, I searched some time for this solution.
Installing mono-devel worked (debian testing)

**Comment by lopho** [comment] 2019-02-07 12:52
Don't install mono-devel, that's an uninformed scattershot. It pulls in a lot of unnecessary packages. Just install the mono compiler, ```mono-mcs``` on Debian systems. It is required to compile the plugin for the correct mono version running keepass2. (And possibly install ```libmono-system-management```, if it is not installed).

[rant]\
But seriously, there needs to be a _proper_ list of dependencies for this project, just saying ```mono-complete``` or ```mono-devel``` is not good advice as it just pulls in dozens of unnecessary libraries and sources, and does nothing to educate the user about the system requirements.\
[/rant]

**Comment by dlech** [comment] 2019-02-07 16:41
In the old KeeFox repo, there was a wiki page for this.

https://github.com/kee-org/KeeFox/wiki/en-%7C-Installation-%7C-Linux#install-additional-plugin-dependencies-ubuntu-1604-only

@luckyrat, could we add a wiki page in this repo (or some other easy to find place) with this information?

**Comment by luckyrat** [comment] 2019-02-10 20:34
@lopho - The challenge is that with ongoing Mono, KeePass and distro changes, a list of dependencies is a moving target and not really anything to do with KeePassRPC, rather KeePass itself.

The solution might be to add a link to the Kee [installation instructions](https://forum.kee.pm/t/installing-kee-instructions/23) page to the most up to date information about running KeePass on Linux. To the best I can tell, that is hosted at https://keepass.info/help/v2/setup.html#mono

That page concludes that installing mono-complete is the correct approach if you want to load plugins but I do see the point that it would be nice to come up with a more specific list of dependencies, if such a task is feasible.

Maybe one of the Linux experts here wants to start a discussion on the KeePass support forum about improving that page?

@dd8zc This information is written in the installation instructions and the [troubleshooting guide](https://forum.kee.pm/t/troubleshooting/560#heading--keepass-plugin-could-not-be-loaded). Do you have some suggestion for where else it should be put?

If we're confident that the instructions on the page @dlech linked to will work for a majority of distros, I'm happy to add that as the recommended approach on the installation instructions page rather than just installing mono-complete. I'm just wary of creating a huge page with a different list of dependencies for every possible distro out there, and perhaps that's the reason the official KeePass website suggests mono-complete too.

**Comment by luckyrat** [comment] 2019-03-01 15:46
I'm closing this issue now. It was left open primarily to aid discoverability for users that jump to GitHub issues before reading the release notes. I'm hopeful that the new "Similar issues" list displayed when users start opening a new issue will serve a similar purpose.

If there are any outstanding issues buried within these comments (e.g. around documentation changes) please open a new issue that is specific to that issue, or better yet discuss on the [community forum](https://forum.kee.pm).

**Closed as completed by luckyrat** 2019-03-01 15:46 UTC
Labels: invalid

**Comment by assarbad** [comment] 2024-03-30 00:45
FYI, using it on Mint 21.3 (based on Ubuntu 22.04) with the following packages works for me:

```
$ dpkg -l|awk '$1 == "ii" && $2 ~ /^(lib)?mono-/ {print $2}'
libmono-accessibility4.0-cil
libmono-btls-interface4.0-cil
libmono-corlib4.5-cil
libmono-corlib4.5-dll
libmono-csharp4.0c-cil
libmono-i18n-west4.0-cil
libmono-i18n4.0-cil
libmono-microsoft-csharp4.0-cil
libmono-posix4.0-cil
libmono-security4.0-cil
libmono-system-configuration-install4.0-cil
libmono-system-configuration4.0-cil
libmono-system-core4.0-cil
libmono-system-data4.0-cil
libmono-system-drawing4.0-cil
libmono-system-enterpriseservices4.0-cil
libmono-system-management4.0-cil
libmono-system-numerics4.0-cil
libmono-system-runtime-serialization-formatters-soap4.0-cil
libmono-system-security4.0-cil
libmono-system-transactions4.0-cil
libmono-system-windows-forms4.0-cil
libmono-system-xml4.0-cil
libmono-system4.0-cil
libmono-webbrowser4.0-cil
mono-4.0-gac
mono-gac
mono-mcs
mono-runtime
mono-runtime-common
mono-runtime-sgen
```

I, too, was annoyed by the absence of some solution other than the recommended installation of `mono-complete`.
